#*****************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# recreate_project.tcl: Tcl script for re-creating project 'final_project'
#
# Generated by Vivado on Wed Mar 20 22:15:35 PDT 2019
# IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (recreate_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/boards/debounce.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/generic/delaybyx.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/dtg.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_const.vh"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_7sd.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_7sd_decoder.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_7sd_driver.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_XADC.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_audio.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/mfp_ahb_b_ram.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_gpio.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/mfp_ahb_p_ram.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_sprite_ram.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_sprite_table_ram.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_timer.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb_withloader.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ejtag_reset.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_srec_parser.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_srec_parser_to_ahb_lite_bridge.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_const.vh"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_config.vh"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_sys.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_uart_receiver.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_b0.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_b1.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_b2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_b3.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_p0.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_p1.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_p2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/ram_p3.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/sprite_ram_b0.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/sprite_sort.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/memories/sprite_table_ram.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/boards/top_xadc_stuff.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/generic/basic_counter.sv"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/colorizer.sv"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/generic/fancy_counter.sv"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/icon.sv"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/system/mfp_ahb.sv"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/mfp_to_sprite_table_decoder.sv"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/sprite_man.sv"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/boards/nexys4_ddr/mfp_nexys4_ddr.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/true_dpram_sclk.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/generic/delayby1.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cdmmstub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_edp_buf_misc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tap_dasamstub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tap_fdcstub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tap_pcsamstub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_udi_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/ram_dual_port.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/ram_reset_dual_port.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/generic/clog2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/video/palette.txt"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/RAMB4K_S16.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/RAMB4K_S2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/RAMB4K_S8.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_config.vh"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_const.vh"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/d_wsram_2k2way_xilinx.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/dataram_2k2way_xilinx.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/i_wsram_2k2way_xilinx.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dsp_const.vh"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_alu_dsp_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_alu_shft_32bit.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_bistctl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_biu.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cache_cmp.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cache_mux.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cdmm.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cdmm_ctl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cdmm_mpustub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_clock_buf.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_clock_nogate.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_clockandlatch.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_clockxnorgate.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cop1_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cop2_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_core.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cp1_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cp2_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpu.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_antitamper_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_eicoffset_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_guest_srs1.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_guest_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_pc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_pc_top.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_prid.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_root_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_sps_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_srs1.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cpz_watch_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cscramble_scanio_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cscramble_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_cscramble_tpl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dc_bistctl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dcc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dcc_fb.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dcc_mb_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dcc_parity_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dcc_spmb_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dcc_spstub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_dspram_ext_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_edp.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_edp_add_simple.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_edp_buf_misc_pro.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_edp_clz.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_edp_clz_16b.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_edp_clz_4b.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_and2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_area.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_async_rec.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_async_snd.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_brk21.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_bus32mux2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_dbrk.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_fifo_1r1w_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_gate.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_ibrk.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_mux2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_pdttcb_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tap.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tap_dasam.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tap_fdc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tap_pcsam.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tck.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ejt_tripsync.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_fpuclk1_nogate.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_gf_mux2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_glue.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ic.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ic_bistctl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_icc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_icc_mb_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_icc_parity_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_icc_spmb_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_icc_spstub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_icc_umips_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_ispram_ext_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mdl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mdl_add_simple.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mdl_ctl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mdl_dp.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mmu.vh"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mmuc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mpc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mpc_ctl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mpc_dec.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_mpc_exc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_rf_reg.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_rf_rngc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_rf_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_siu.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_siu_int_sync.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_spram_top.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_collector.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_cpy.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_ctl.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_dtlb.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_itlb.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_jtlb16.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_jtlb16entries.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_jtlb1entry.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_jtlb4entries.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_utlb.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_tlb_utlbentry.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_udi_custom.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_udi_scanio_stub.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_cregister.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_cregister_c.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_cregister_ngc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_cregister_s.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_cregister_wide.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_cregister_wide_tlb.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_cregister_wide_utlb.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_latchn.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux16.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_10.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_13.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_24.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_3.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_4.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_5.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_6.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_8.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux1hot_9.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux2.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux4.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_mux8.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_register.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_register_c.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_register_ngc.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_register_s.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/mvp_ucregister_wide.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/tagram_2k2way_xilinx.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/core/m14k_top.v"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/constraints/mfp_m14k_top.xdc"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/ip_blocks/xadc_wiz_0/xadc_wiz_0.xci"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/ip_blocks/clk_wiz_0/clk_wiz_0.xci"
#    "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk/rtl_up_v3/constraints/mfp_nexys4_ddr.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "/home/rattboi/code/finalproj-brianh_grantv_jamie-w_bradonk"

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "final_project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "recreate_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/final_project"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.uses_pr" -value "1" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "13" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "13" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "13" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "13" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "13" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "13" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "13" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/rtl_up_v3/boards/debounce.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/generic/delaybyx.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/dtg.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_const.vh"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_7sd.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_7sd_decoder.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_7sd_driver.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_XADC.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_audio.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/mfp_ahb_b_ram.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_gpio.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/mfp_ahb_p_ram.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_sprite_ram.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_sprite_table_ram.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_timer.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb_withloader.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ejtag_reset.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_srec_parser.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_srec_parser_to_ahb_lite_bridge.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_const.vh"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_config.vh"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_sys.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_uart_receiver.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_b0.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_b1.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_b2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_b3.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_p0.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_p1.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_p2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/ram_p3.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/sprite_ram_b0.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/sprite_sort.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/memories/sprite_table_ram.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/boards/top_xadc_stuff.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/generic/basic_counter.sv"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/colorizer.sv"] \
 [file normalize "${origin_dir}/rtl_up_v3/generic/fancy_counter.sv"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/icon.sv"] \
 [file normalize "${origin_dir}/rtl_up_v3/system/mfp_ahb.sv"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/mfp_to_sprite_table_decoder.sv"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/sprite_man.sv"] \
 [file normalize "${origin_dir}/rtl_up_v3/boards/nexys4_ddr/mfp_nexys4_ddr.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/true_dpram_sclk.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/generic/delayby1.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cdmmstub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_edp_buf_misc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tap_dasamstub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tap_fdcstub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tap_pcsamstub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_udi_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/ram_dual_port.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/ram_reset_dual_port.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/generic/clog2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/video/palette.txt"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/rtl_up_v3/system/mfp_ahb_const.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl_up_v3/core/m14k_const.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl_up_v3/core/m14k_config.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl_up_v3/generic/basic_counter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl_up_v3/video/colorizer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl_up_v3/generic/fancy_counter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl_up_v3/video/icon.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl_up_v3/system/mfp_ahb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl_up_v3/video/mfp_to_sprite_table_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl_up_v3/video/sprite_man.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "mfp_nexys4_ddr" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'm14k_top' fileset (if not found)
if {[string equal [get_filesets -quiet m14k_top] ""]} {
  create_fileset -blockset m14k_top
}

# Set 'm14k_top' fileset object
set obj [get_filesets m14k_top]
set files [list \
 [file normalize "${origin_dir}/rtl_up_v3/core/RAMB4K_S16.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/RAMB4K_S2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/RAMB4K_S8.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_config.vh"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_const.vh"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/d_wsram_2k2way_xilinx.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/dataram_2k2way_xilinx.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/i_wsram_2k2way_xilinx.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dsp_const.vh"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_alu_dsp_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_alu_shft_32bit.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_bistctl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_biu.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cache_cmp.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cache_mux.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cdmm.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cdmm_ctl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cdmm_mpustub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_clock_buf.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_clock_nogate.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_clockandlatch.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_clockxnorgate.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cop1_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cop2_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_core.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cp1_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cp2_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpu.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_antitamper_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_eicoffset_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_guest_srs1.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_guest_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_pc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_pc_top.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_prid.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_root_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_sps_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_srs1.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cpz_watch_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cscramble_scanio_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cscramble_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_cscramble_tpl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dc_bistctl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dcc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dcc_fb.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dcc_mb_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dcc_parity_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dcc_spmb_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dcc_spstub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_dspram_ext_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_edp.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_edp_add_simple.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_edp_buf_misc_pro.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_edp_clz.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_edp_clz_16b.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_edp_clz_4b.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_and2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_area.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_async_rec.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_async_snd.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_brk21.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_bus32mux2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_dbrk.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_fifo_1r1w_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_gate.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_ibrk.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_mux2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_pdttcb_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tap.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tap_dasam.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tap_fdc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tap_pcsam.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tck.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ejt_tripsync.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_fpuclk1_nogate.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_gf_mux2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_glue.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ic.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ic_bistctl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_icc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_icc_mb_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_icc_parity_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_icc_spmb_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_icc_spstub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_icc_umips_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_ispram_ext_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mdl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mdl_add_simple.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mdl_ctl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mdl_dp.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mmu.vh"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mmuc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mpc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mpc_ctl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mpc_dec.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_mpc_exc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_rf_reg.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_rf_rngc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_rf_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_siu.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_siu_int_sync.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_spram_top.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_collector.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_cpy.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_ctl.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_dtlb.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_itlb.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_jtlb16.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_jtlb16entries.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_jtlb1entry.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_jtlb4entries.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_utlb.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_tlb_utlbentry.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_udi_custom.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_udi_scanio_stub.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_cregister.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_cregister_c.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_cregister_ngc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_cregister_s.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_cregister_wide.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_cregister_wide_tlb.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_cregister_wide_utlb.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_latchn.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux16.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_10.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_13.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_24.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_3.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_4.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_5.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_6.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_8.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux1hot_9.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux2.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux4.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_mux8.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_register.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_register_c.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_register_ngc.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_register_s.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/mvp_ucregister_wide.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/tagram_2k2way_xilinx.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/core/m14k_top.v"] \
 [file normalize "${origin_dir}/rtl_up_v3/constraints/mfp_m14k_top.xdc"] \
]
add_files -norecurse -fileset $obj $files

# Set 'm14k_top' fileset file properties for remote files
set file "$origin_dir/rtl_up_v3/core/m14k_config.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets m14k_top] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl_up_v3/core/m14k_const.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets m14k_top] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl_up_v3/core/m14k_dsp_const.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets m14k_top] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl_up_v3/core/m14k_mmu.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets m14k_top] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/rtl_up_v3/constraints/mfp_m14k_top.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets m14k_top] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation out_of_context" -objects $file_obj


# Set 'm14k_top' fileset file properties for local files
# None

# Set 'm14k_top' fileset properties
set obj [get_filesets m14k_top]
set_property -name "top" -value "m14k_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_file" -value "rtl_up_v3/core/m14k_top.v" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip_blocks/xadc_wiz_0/xadc_wiz_0.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip_blocks/xadc_wiz_0/xadc_wiz_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip_blocks/clk_wiz_0/clk_wiz_0.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip_blocks/clk_wiz_0/clk_wiz_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/rtl_up_v3/constraints/mfp_nexys4_ddr.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/rtl_up_v3/constraints/mfp_nexys4_ddr.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7a100tcsg324-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "mfp_nexys4_ddr" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# Create 'm14k_top_synth_1' run (if not found)
if {[string equal [get_runs -quiet m14k_top_synth_1] ""]} {
    create_run -name m14k_top_synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset m14k_top
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs m14k_top_synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs m14k_top_synth_1]
}
set obj [get_runs m14k_top_synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'm14k_top_synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_synth_1] m14k_top_synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name m14k_top_synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs m14k_top_synth_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_synth_1] m14k_top_synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs m14k_top_synth_1]
set_property -name "constrset" -value "m14k_top" -objects $obj
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# Create 'm14k_top_impl_1' run (if not found)
if {[string equal [get_runs -quiet m14k_top_impl_1] ""]} {
    create_run -name m14k_top_impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2018} -strategy "Flow_Quick" -report_strategy {No Reports} -constrset m14k_top -parent_run m14k_top_synth_1
} else {
  set_property strategy "Flow_Quick" [get_runs m14k_top_impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs m14k_top_impl_1]
}
set obj [get_runs m14k_top_impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'm14k_top_impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name m14k_top_impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'm14k_top_impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'm14k_top_impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name m14k_top_impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs m14k_top_impl_1
}
set obj [get_report_configs -of_objects [get_runs m14k_top_impl_1] m14k_top_impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs m14k_top_impl_1]
set_property -name "constrset" -value "m14k_top" -objects $obj
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "include_in_archive" -value "0" -objects $obj
set_property -name "strategy" -value "Flow_Quick" -objects $obj
set_property -name "steps.opt_design.args.directive" -value "ExploreSequentialArea" -objects $obj
set_property -name "steps.place_design.args.directive" -value "EarlyBlockPlacement" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.phys_opt_design.args.directive" -value "AlternateFlowWithRetiming" -objects $obj
set_property -name "steps.route_design.args.directive" -value "AlternateCLBRouting" -objects $obj
set_property -name "steps.post_route_phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.post_route_phys_opt_design.args.directive" -value "ExploreWithAggressiveHoldFix" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
